title: BorgBase Docs
description: All the resources you need to develop a comprehensive backup strategy with BorgBase and apply it in your environment.
baseurl: ""
url: "https://docs.borgbase.com"

permalink: pretty
include: ["_redirects"]
exclude: ["README.md", "Rakefile"]

search_enabled: true
heading_anchors: true

permalink: /404.html

aux_links:
  "Get 10 GB Free Backup Hosting":
    - "https://www.borgbase.com"

theme: just-the-docs
color_scheme: borgbase
callouts:
  note:
    title: Note
    color: grey-dk

kramdown:
  toc_levels: 1..3

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # https://github.com/Ovski4/jekyll-tabs
  - jekyll-tabs